### ISSUE TITLE
How to repeat play?

### ISSUE THREAD

**Issue by sunjianan9900** [huma11farheen/hop_swipe_cards#2]
great project
but i cant repeat play image

**Comment by huma11farheen** [comment]
@sunjianan9900 
That feature is not added but what exactly are you trying to achieve?

**Comment by sunjianan9900** [comment]
> @sunjianan9900
> That feature is not added but what exactly are you trying to achieve?

i set 30 pictures here , and when i finish drop all these pic, there's no way to return to the first one, only show the noMoreSwipeCardsLeft widget. i wonder if it can loop around
and i refresh my pictures list , but not show the new pic on screen .

不知道你能不能看得懂中文，就是说现在所有图片滑动完之后，就会卡在noMoreSwipeCardsLeft页面上，无法继续。
是否可以加一个参数，允许无限循环地滑动。
另外比如我设置了30个图片，快要滑动完的时候我又加载了30个，这个时候如果加到图片的list里面，由于length变化了，会导致从0开始播放，这样用户就需要重复查看前30个。
也就是说contraller不能指定跳转到第几个。。。

说的有点多，主要是希望考虑两个问题：
（1）如何循环播放？
（2）如何动态追加数据到正在播放的list里？

**Comment by huma11farheen** [comment]
@sunjianan9900 
Sure, this can be added, will update you soon

**Comment by sunjianan9900** [comment]
> @sunjianan9900
> Sure, this can be added, will update you soon

thanks a lot ～
